### ISSUE TITLE
#1 sign up process: username

### ISSUE THREAD

**Issue by gadgetmuc** [gadgetmuc/capstone#1]
## Value Statement
As an __unregistered__ user,
__I need to__ to be able to input my name in the respective \<input /\>
__so that I can__ sign up.

## Acceptance criteria
- [ ] The username I type in must be verified: 2 <= strlen <=30.
- [ ] The username has to be alphanumerical without spaces (" ") and must not include special characters except for hyphen, underscore, dot (".").
- [ ] The database will be checked for duplicates when pressing \<submit /\>
- [ ] As long as any of the criteria are not matched, the \<submit /\>-Button will be _disabled_. 
- [ ] If the input username does not match the criteria, the \<input /\> border will turn red and a message will be shown.
- [ ] The username is mandatory to proceed the registration process.

## Tasks
- [ ] create username input for sign up form
- [ ] add user input validation to front end 
- [ ] write test
- [ ] create design
- [ ] add logic to backend
- [ ] add req/res to/from server

## Complexity
SM
