### ISSUE TITLE
#10 sign in process: sign in page

### ISSUE THREAD

**Issue by gadgetmuc** [gadgetmuc/capstone#10]
## Value Statement
As an __registered__ user,
__I need to__ be shown a sign in page 
__so that I can__ sign in.

## Acceptance criteria
- [ ] headline, buttons, input fields and labels for each query
- [ ] the page shows the input fields, labels and buttons for signing in
- [ ] the page also shows a label and a button for yet unregistered users; they will be redirected to the sign up page

## Tasks
- [ ] write test
- [ ] add req/res to/from server
- [ ] add headline
- [ ] add input field for user name
- [ ] add input field for email address
- [ ] add labels for input fields
- [ ] add sign in-button
- [ ] add cancel-button
- [ ] add navigation with active highlighting

## Complexity
M
