### ISSUE TITLE
#11 article categories page: under the hood

### ISSUE THREAD

**Issue by gadgetmuc** [gadgetmuc/capstone#11]
## Value Statement
As an user,
__I need to__ be shown the article categories page in a useful way
__so that I can__ choose which kind of groceries I want to add to my list without (reading too small) text.

![grafik](https://user-images.githubusercontent.com/30418535/100028262-d1c8db80-2dee-11eb-93f5-dbf7ff620176.png)

## Acceptance criteria
- [ ] all \<buttons /\> show an image of their respective category
- [ ] navigation buttons at the bottom ("categories", "basket", "login") with active highlighting

## Tasks 
- [ ] each button opens the respective overlay
- [ ] buttons with images 
- [ ] design navigation buttons (active and normal)
- [ ] navigation buttons redirect to the respective pages
- [ ] background image
- [ ] blur and fade fx

## Complexity
L
