### ISSUE TITLE
#14 database: setup/connection/relations  [tbd]

### ISSUE THREAD

**Issue by gadgetmuc** [gadgetmuc/capstone#14]

**Comment by gadgetmuc** [comment]
## Value Statement
As an user,
__I need to__ have a database and a connection to it
__so that I can__ do things like log in, put articles into my shopping cart or share my list with other users.

## Acceptance criteria
- [x] the database is filled with some data to start with
- [ ] the frontend can talk to the backend

## Tasks 
- [x] build tables and migrate them
- [ ] relations 
- [ ] write fetches for frontend
- [ ] test them

## Complexity
L
