### ISSUE TITLE
#2 sign up process: email

### ISSUE THREAD

**Issue by gadgetmuc** [gadgetmuc/capstone#2]
## Value Statement
As an __unregistered__ user,
__I need to__ to be able to input my email in the respective \<input /\>
__so that I can__ sign up.

## Acceptance criteria
- [ ] The mail address must be conform with RFC5322 (no IDN, ASCII < 127)
- [ ] no (!) validation for punycode or utf-8 to keep it simple
- [ ] no single letter SLD allowed, check for minimum 2 letter SLD
- [ ] check for minimum 2 letter TLD
- [ ] no capital letters
- [ ] the local part must only use these characters: A-Za-z0-9.!#$%&'*+-/=?^_`{}|~
- [ ] "\" and "@" within the local part (!) must be escaped
- [ ] the local part must not begin or end with a dot (".").
- [ ] 

- [ ] The database will be checked for duplicates when pressing \<submit /\>
- [ ] As long as any of the criteria are not matched, the \<submit /\>-Button will be _disabled_. 
- [ ] If the input email does not match the criteria, the \<input /\> border will turn red and a message will be shown.
- [ ] The email is mandatory to proceed the registration process.

## Tasks
- [ ] create email input for sign up form
- [ ] add user input validation to front end 
- [ ] write test
- [ ] create design
- [ ] add logic to backend
- [ ] add req/res to/from server

## Complexity
SM
