### ISSUE TITLE
#3 sign up process: password

### ISSUE THREAD

**Issue by gadgetmuc** [gadgetmuc/capstone#3]

**Comment by gadgetmuc** [comment]
## Value Statement
As an __unregistered__ user,
__I need to__ to be able to input my password _twice_ in the respective \<input /\> ("enter password" & "confirm password")
__so that I can__ sign up.

## Acceptance criteria
- [ ] passwords must consist of minimum 8 characters
- [ ] passwords must include A-Z, a-z, 0-9, and at least one special character: .!#$%&*+-=?^_{}|~
- [ ] As long as any of the criteria are not matched, the \<submit /\>-Button will be _disabled_. 
- [ ] If the input password/s do/es not match the criteria, the \<input /\> border will turn red and a message will be shown.
- [ ] The password is mandatory to proceed the registration process.
- [ ] if both of the input passwords match, place something green behind the \<input /\>

## Tasks
- [ ] create two (!) password inputs for sign up form
- [ ] write comparision during input
- [ ] add the green little something
- [ ] add user input validation to front end 
- [ ] write test
- [ ] create design
- [ ] add logic to backend
- [ ] add req/res to/from server

## Complexity
SM
