### ISSUE TITLE
#4 sign up process: submit-button

### ISSUE THREAD

**Issue by gadgetmuc** [gadgetmuc/capstone#4]
## Value Statement
As an __unregistered__ user,
__I need to__ to be able to hit <Submit />
__so that I can__ complete the sign up process.

## Acceptance criteria
- [ ] button stays disabled until all the inputs are filled in correctly (according to their respective AC, that is)
- [ ] button has some text ("ok" or "weiter" or sth like that) and an according symbol

## Tasks
- [ ] create button with text and symbol
- [ ] toggle active/disabled 
- [ ] write test
- [ ] create design
- [ ] add req/res to/from server

## Complexity
S
