### ISSUE TITLE
#5 sign up process: sign up page

### ISSUE THREAD

**Issue by gadgetmuc** [gadgetmuc/capstone#5]
## Value Statement
As an __unregistered__ user,
__I need to__ be shown a sign up page 
__so that I can__ go through sign up process.

## Acceptance criteria
- [ ] the page will show an overlay over the sign in-page
- [ ] so it has the same elements as the sign in-page beyond, but they do not function 
- [ ] headline, buttons, input fields and labels for each query
- [ ] the cancel button redirects to the sign in-page

## Tasks
- [ ] write test
- [ ] add req/res to/from server
- [ ] add headline
- [ ] add the elements of the sign in-page in the back
- [ ] add overlay
- [ ] add input field for user name
- [ ] add input field for email address
- [ ] add input fields for password (twice)
- [ ] add submit-button
- [ ] add cancel-button
- [ ] add navigation with active highlighting

## Complexity
S
