### ISSUE TITLE
#6 article categories page: mockup/design

### ISSUE THREAD

**Issue by gadgetmuc** [gadgetmuc/capstone#6]
## Value Statement
As an user,
__I need to__ be shown the article categories page in a useful way
__so that I can__ choose which kind of groceries I want to add to my list without (reading too small) text.

![grafik](https://user-images.githubusercontent.com/30418535/100028262-d1c8db80-2dee-11eb-93f5-dbf7ff620176.png)

## Acceptance criteria
- [x] all \<buttons /\> show an image of their respective category
- [x] there are categories like vegetables, fruit, beverages, milk/cheese, products for babies, drugstore,
- [x] navigation buttons at the bottom ("categories", "basket", "login") with active highlighting

## Tasks 
- [x] categorize the articles into the actual amount of categories
- [x] design buttons with images 
- [x] design navigation buttons (active and normal)
- [x] overall site design
- [x] shopping-related background image
- [x] blur and fade fx
- [ ] actual mockup

## Complexity
M
