### ISSUE TITLE
#7 articles to choose from within a category page: mockup/design

### ISSUE THREAD

**Issue by gadgetmuc** [gadgetmuc/capstone#7]
## Value Statement
As an user,
__I need to__ be shown the article within a category
__so that I can__ go through the list and make my choices.

![articles screen](https://user-images.githubusercontent.com/30418535/100028701-cb872f00-2def-11eb-97f2-7376310c75f8.png)

## Acceptance criteria
- [x] articles are shown in alphabetical order 
- [x] the list is scrollable
- [x] there is no scrollbar
- [x] the amount of articles can be changed individually using [+]/[-] - raising or lowering the amount by 1
- [x] each item reads an article of that respective _category_ on the left
- [x] navigation buttons at the bottom ("categories", "basket", "login") with active highlighting
- [x] header contains a small category's image, the name of the category and a "go back" \<Button /\>
- [x] items are rendered on a semi-opaque blurred overlay

## Tasks 
- [x] design buttons for articles 
- [x] design navigation buttons (active and normal)
- [x] design header
- [x] overall site design including overlay
- [x] shopping-related background image
- [x] blur and fade fx
- [ ] actual mockup

## Complexity
M
