### ISSUE TITLE
#8 Shopping cart page: mockup/design

### ISSUE THREAD

**Issue by gadgetmuc** [gadgetmuc/capstone#8]

**Comment by gadgetmuc** [comment]
## Value Statement
As an user,
__I need to__ see the articles in my shopping cart
__so that I can__ collect all of which are located within an area.

![shoppinglist screen](https://user-images.githubusercontent.com/30418535/100030159-279f8280-2df3-11eb-9c6e-5ae5b1f2d1ed.png)

## Acceptance criteria
- [x] several items (as many as there are in the shopping cart)...
- [x] ...reading the article name on the left
- [x] on the right, there is a _minus_-\<Button /\>, a _plus_-\<Button /\> and a label that reads the amount of that very article
- [x] navigation buttons at the bottom ("categories", "basket", "login") with active highlighting
- [x] header has a headline saying "Einkaufsliste"
- [x] items are rendered on a semi-opaque blurred overlay

## Tasks 
- [x] design article items 
- [x] design navigation buttons (active and normal)
- [x] design header
- [x] overall page design including overlay
- [x] shopping-related background image
- [x] blur and fade fx
- [ ] actual mockup

## Complexity
M
