### ISSUE TITLE
#9 sign up page: mockup/design

### ISSUE THREAD

**Issue by gadgetmuc** [gadgetmuc/capstone#9]
## Value Statement
As an user,
__I need to__ see the sign up screen
__so that I can__ sign up and have my data saved to the database

![sign up screen](https://user-images.githubusercontent.com/30418535/100141250-68020d80-2e92-11eb-8452-ed7aad689e09.png)

## Acceptance criteria
- [x] a headline for the page
- [x] an input field for the user name
- [x] an input field for the email address
- [x] two input fields for entering the password twice
- [x] labels for each input field
 
## Tasks 
- [ ] design input fields (all have the same styling)
- [x] design navigation buttons (active and normal)
- [x] header says sth like "sign up" 
- [x] overall page design including overlay
- [x] shopping-related background image
- [x] blur and fade fx
- [ ] actual mockup

## Complexity
S
